---

- name: install pkg
  yum:
    pkg={{ntp_pkg_name}}
    state={{ntp_pkg_state}}

- name: config
  template: 
    src=ntp-{{ansible_os_family}}-{{ansible_distribution_major_version}}.conf.j2
    dest=/etc/ntp.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: svc restart ntp

- name: enable, start
  service:
    name={{ntp_svc_name}}
    state={{ntp_svc_state}}
    enabled={{ntp_svc_enabled}}

